AWSTemplateFormatVersion: "2010-09-09"
Description: "EKS Cluster Create"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Name Prefix
        Parameters:
          - NamePrefix
      - Label:
          default: EKS Cluster Configuration
        Parameters:
          - EKSClusterName
          - EKSClusterSecurityGroupIds
          - EKSClusterSubnetId1
          - EKSClusterSubnetId2
          - EKSClusterSubnetId3
          - EKSClusterSubnetId4
          - EKSVersion

Parameters:
  NamePrefix:
    Type: String
  EKSClusterName:
    Description: "Same as EKSClusterName which you input in VPC template."
    Type: String
  EKSClusterSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  EKSClusterSubnetId1:
    Type: AWS::EC2::Subnet::Id
  EKSClusterSubnetId2:
    Type: AWS::EC2::Subnet::Id
  EKSClusterSubnetId3:
    Type: AWS::EC2::Subnet::Id
  EKSClusterSubnetId4:
    Type: AWS::EC2::Subnet::Id
  EKSVersion:
    Type: String
    Default: "1.20"

Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${NamePrefix}-EKSCluster-Role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
        Version: "2012-10-17"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
        - "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"
      Path: "/"

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref EKSClusterName
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref EKSClusterSecurityGroupIds
        SubnetIds:
          - !Ref EKSClusterSubnetId1
          - !Ref EKSClusterSubnetId2
          - !Ref EKSClusterSubnetId3
          - !Ref EKSClusterSubnetId4
        EndpointPublicAccess: false
        EndpointPrivateAccess: true
      RoleArn: !GetAtt ClusterRole.Arn
      Version: !Ref EKSVersion

Outputs:
  EKSClusterRoleArn:
    Value: !GetAtt ClusterRole.Arn
  EKSClusterName:
    Value: !Ref EKSCluster

