apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <your EKS cluster name>
  region: ap-northeast-1

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
    subnets:
      - <your private subnet a>
      - <your private subnet c>
  - name: fp-sample-ns
    selectors:
      - namespace: sample-ns
    subnets:
      - <your private subnet a>
      - <your private subnet c>
